sudo: required
script:
- sass main.scss build/matdark.css;
- sass matlight.scss build/matlight.css;
- php build/invert-css matlight.css build/matlight.css;

language: sass
before_install:
- sudo gem install sass
